csf/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve


from . import views

app_name = 'csf'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('products', views.product_view, name='products'),
    path('products/<sub_category>/', views.product_view, name='products'),
    path('download/<int:product_id>', views.download_file, name='download_file'),
    path('cart', views.cart_view, name='cart'),
    path('cart/<item_to_remove>', views.cart_view, name='cart'),
    path('sent', views.send_view, name='sent'),
    path('faq', views.faq_view, name='faq'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csf_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('csf.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>
    {% load bootstrap_icons %}

    {% block sidebar %}
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #fcfeff">
      <div class="container-fluid">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
              <li class="nav-item" style="padding-right:50px">
                 <a class="navbar-brand mx-auto" href="{{request.META.HTTP_NAME}}/">
                    <img src="{% static 'csf_logo.jpg' %}" alt="logo" height="150" width="450"/>
                 </a>
              </li>
          </ul>
        </div>
      </div>
    </nav>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #c32434;">
      <div class="container-fluid justify-content-center">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <div class="navbar-nav me-auto">
            <form class="d-flex" method="POST">
              {% csrf_token %}
              <input class="form-control me-2 autocomplete" id="search" name="search" type="search" placeholder="Search Products" aria-label="Search" style="width: 75%">
              <button class="btn btn-light" type="submit">
                <span>{% bs_icon 'search' %}</span>
              </button>
            </form>
              <script>
                  $( function() {
                    var availableProd = [
                        {% for choice in autocomplete_choices %}
                            "{{choice.name}}",
                        {% endfor %}
                    ];
                    $( "#search" ).autocomplete({
                      source: availableProd
                    });
                  } );
              </script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js"></script>
            <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css"
                  rel="stylesheet" type="text/css" />
          </div>
          <ul class="navbar-nav" style="font-size: larger; padding-right: 9rem;">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{request.META.HTTP_NAME}}/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/products">Products</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/faq">FAQ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#footer">Legal</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#footer">Contact</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto" style="font-size: larger">
            <li class="nav-item">
              {% if num_quotes %}
                <a href="/cart" class="btn btn-light">
                  <span style="padding-right: 5px;">{% bs_icon 'cart' %}</span>
                  View Cart
                  <span style="padding-right: 5px;"></span>
                  <span class="badge bg-dark">{{num_quotes}}</span>
                </a>
              {% else %}
                <a href="/cart" class="btn btn-light">
                  <span style="padding-right: 5px;">{% bs_icon 'cart' %}</span> View Cart
                </a>
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% endblock %}

      <title>Carolina Stainless Fabrication</title>

  </head>
  <body>
    <link rel="stylesheet" type="text/css" href="{% static 'css/homepage.css' %}"/>

    {% block content %}
      <!-- default content text (typically empty) -->
    {% endblock %}
  </body>

<!-- Footer -->
<footer id="footer" class="text-center text-lg-start text-muted">

  <section class="">
    <div class="text-center" style="background-color: #212529; padding-top: 20px;">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>About Our Steel
          </h6>
          <p>
            At Carolina Stainless Fabrication, we use AISI 304 Stainless Steel with a No. 4 finish due to its
            ideal properties fit for the food and beverage industry. AISI 304 is a steel alloy that has
            tremendous resistance to corrosion and rust due to an oxide layer created by high chromium
            (18%) and nickel (8%) content. This metal composition is non-reactive with a non-porous surface,
            meaning it prevents the material from transmitting any color, odor, or taste to products it
            encounters. Aside from having high temperature tolerance and durability, ASIS 304 follows
            regulatory standards and requirements needed for food contact materials (FDA and NSF
            International).
          </p>
        </div>

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Legal
          </h6>
          <p>
            All of our products have been investigated by UL in accordance with the standards of:
          </p>
          <p>
            NFPA 70 National Electrical Code Sections 392.60(A) and 392.60(B) NEMA VE1 METAL
            CABLE AND TRAY SYSTEMS CSA C22.2 NO. 126.1-17 METAL CABLE TRAY SYSTEMS
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> 7073 W Highway 290 <br>Dripping Spring, Tx 78620 United States</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            andrewbell@carolinastainlessfabrication.com
          </p>
          <p><i class="fas fa-phone me-3"></i> +1 (512) 621-4747</p>
          <p><i class="fas fa-print me-3"></i> some other number</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

</footer>
<!-- Footer -->
</html>

templates/cart.html
{% extends "base.html" %}

{% block content %}
    {% load static %}
    {% load csf_tags %}
    {% load bootstrap_icons %}
    {% load crispy_forms_tags %}

    {% if form %}
        <script type="text/javascript">
            $(window).on('load', function() {
                $('#contact_modal').modal('show');
            });
        </script>
    {% endif %}

    <div class="d-flex justify-content-center" style="margin-top: 50px; margin-bottom: 15rem;">
        {% if quote_items %}
            <div class="card">
              <div class="card-body d-flex justify-content-center">
                <form action="" method="POST">
                {% csrf_token %}
                    <div class="row d-flex " style="width: 35rem; padding-bottom: 1rem;">
                        <div class="col justify-content-center"></div>
                      <div class="col justify-content-center"></div>
                      <div class="col justify-content-center">Size</div>
                      <div class="col justify-content-center">Quantity</div>
                      <div class="col justify-content-center">Remove</div>
                    </div>
                  {% for item in quote_items%}
                    <div class="row d-flex " style="width: 35rem; padding-bottom: 1rem;">
                        <div class="col ms-auto">
                            <img src="{{item|getimage}}" class="img-thumbnail">
                        </div>
                        <br>
                        <div class="col justify-content-center">{{item|getname}}</div>
                        <div class="col justify-content-center">
                            <select name="{{item|makename:'size'}}" class="form-select" aria-label="Default select example" style="padding-left: 10px; padding-right: 10px;">
                                <option selected>{{item|size}}</option>
                                {% for size in item|getsizes %}
                                    <option value="{{ size }}">{{ size }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col justify-content-center">
                            <input name="{{item|makename:'quantity'}}" min="0" max="1000" type="number" id="typeNumber" class="form-control" value="{{item|quantity}}" style="width: 5rem">
                        </div>
                        <div class="col justify-content-center">
                            <a href="{{request.META.HTTP_NAME}}/cart/{{item|getid}}"><span style="padding-left: 30%;" >{% bs_icon 'x' color='red'%}</span></a>
                        </div>
                    </div>
                  {% endfor %}
                    <div class="row">
                        <div class="card-footer d-flex justify-content-between">
                    <a href="products" class="btn btn-dark"><span style="padding-right: 5px;">{% bs_icon 'arrow-left' %}</span>Products</a>
                    <button type="submit" class="btn btn-dark" style="background-color: #c32434;"><span style="padding-right: 5px;">{% bs_icon 'envelope' %}</span>Get Quote</button>
                </div>
                    </div>
                </form>
              </div>
            </div>
        {% else %}
            <div class="card" style="width: 40rem; margin: 20px">
                <div class="card-header d-flex justify-content-center">
                    <h5 class="card-title">No Items in Cart</h5>
                </div>
                <div class="card-body d-flex justify-content-center">
                    <p style="text-align: center;">It looks like you don't have anything in your cart yet. To add items to your cart and get a quote from us, please visit the product page.</p>
                </div>
                <div class="card-footer d-flex justify-content-center">
                  <a href="/products" class="btn btn-secondary">View Products</a>
                </div>
            </div>
        {% endif %}

        <!-- Modal -->
        <div class="modal fade" id="contact_modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="contact_modal_label" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="contact_modal_label">Get Quote</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <p>To receive a quote for the items in your cart, please enter your information and you will be contact shortly.</p>
                <form action="/sent" method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-flex justify-content-end">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <div style="padding-left: 1rem;"></div>
                        <button type="submit" class="btn btn-dark" style="background-color: #c32434;">Send</button>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </div>

    </div>
{% endblock %}

templates/faq.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap_icons %}
    <div class="container d-flex justify-content-center">
        <div class="row d-flex justify-content-center">
            <div class="card" style="width: 65rem; margin: 20px; padding-left: 0px; padding-right: 0px">
                <div class="card-header" style="text-align: center;">
                    <h5 class="card-title">Shipping</h5>
                </div>
                <div class="card-body">
                    <p>Thank you for using the quote request system, you will be emailed a copy of your quote request.</p>
                    <p>We will reach out to you soon regarding you quote.</p>
                    <p> - The Carolina Steel Fabrication Team</p>
                </div>
            </div>
            <div class="card" style="width: 65rem; margin: 20px; padding-left: 0px; padding-right: 0px">
                <div class="card-header" style="text-align: center;">
                    <h5 class="card-title">Our Steel</h5>
                </div>
                <div class="card-body">
                    <p>At Carolina Stainless Fabrication, we use AISI 304 Stainless Steel with a No. 4 finish due to its ideal properties fit for the food and beverage industry.
                        AISI 304 is a steel alloy that has tremendous resistance to corrosion and rust due to an oxide layer created by high chromium (18%) and nickel (8%) content.
                        This metal composition is non-reactive with a non-porous surface, meaning it prevents the material from transmitting any color, odor, or taste to products it encounters.
                        Aside from having high temperature tolerance and durability, ASIS 304 follows regulatory standards and requirements needed for food contact materials (FDA and NSF International).</p>
                </div>
            </div>
            <div class="card" style="width: 65rem; margin: 20px; padding-left: 0px; padding-right: 0px">
                <div class="card-header" style="text-align: center;">
                    <h5 class="card-title">Legal</h5>
                </div>
                <div class="card-body">
                    <p>All of our products have been investigated by UL in accordance with the standards of:</p>
                    <p>NFPA 70 National Electrical Code Sections 392.60(A) and 392.60(B) NEMA VE1 METAL CABLE AND TRAY SYSTEMS CSA C22.2 NO. 126.1-17 METAL CABLE TRAY SYSTEMS</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/product_modal.html
{% extends "products.html" %}

{% block modal %}
  <div class="modal fade" id="quotemodal" tabindex="-1" aria-labelledby="quotemodalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="quotemodalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Understood</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/products.html
{% extends "base.html" %}

{% block content %}
    {%  load static %}
    {% load csf_tags %}

<div class="d-flex justify-content-center" style="margin-top: 50px; margin-bottom: 15rem;">

{#            INTERFACE FOR PRODUCT ACCORDION              #}
        <div class="col d-flex justify-content-center">
            <div class="card" style="width: 25rem;">
                <div class="card-header align-text-center"><h2>Product Ranges</h2></div>
                <div class="accordion accordion-flush" id="accordionFlushExample">
                {% for cat, subcats in categories.items %}
                    {% with "flush-heading-"|add:cat as heading %}
                    {% with "flush-collapse-"|add:cat as collapse %}
                      <div class="accordion-item">
                        <h2 class="accordion-header" id="{{heading|cut:' '}}">
                        {% if selected_category == cat %}
                          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#{{collapse|cut:' '}}" aria-expanded="true" aria-controls="{{collapse|cut:' '}}">
                          {% else %}
                          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#{{collapse|cut:' '}}" aria-expanded="false" aria-controls="{{collapse|cut:' '}}">
                        {% endif %}
                              <h5>{{ cat }}</h5>
                          </button>
                        </h2>
                        {% if selected_category == cat %}
                        <div id="{{collapse|cut:' '}}" class="accordion-collapse collapse show" aria-labelledby="{{heading|cut:' '}}" data-bs-parent="#accordionFlushExample">
                        {% else %}
                        <div id="{{collapse|cut:' '}}" class="accordion-collapse collapse" aria-labelledby="{{heading|cut:' '}}" data-bs-parent="#accordionFlushExample">
                        {% endif %}
                          <div class="accordion-body">
                            <ul class="list-group btn-group d-flex">
                              {% for subcat in subcats %}
                                <li class="list-group-item bg-light" style="margin: 5px">
                                    {% csrf_token %}
                                  <a href="{{request.META.HTTP_NAME}}/products/{{subcat.name|fill_space:'_'}}" class="btn btn-dark w-100" style="background-color: #c32434;">{{subcat.name}}</a>
                                </li>
                              {% endfor %}
                            </ul>
                          </div>
                        </div>
                      </div>
                    {% endwith %} {% endwith %}
                {% endfor %}
                </div>
            </div>
        </div>
{#            Product Cards                #}
        <div class="col">
            <div class="row">
                {% for product in products %}
                <div class="card" style="width: 18rem; margin: 20px">
                  <img src="{{ product.image.url }}" class="card-img-top" alt="item_image">
                  <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.desc }}</p>
                    <select class="form-select" aria-label="Default select example">
                        <option selected>Sizes Available</option>
                        {% for item in product.sizes|process_sizes %}
                            <option value="{{ item }}">{{ item }}</option>
                        {% endfor %}
                    </select>
                      <p style="padding-top: 20px">{{ product.description }}</p>
                      <img src="{% static 'ul1.jpg' %}" height="30px", width="60px">
                  </div>
                    <div class="card-body">
                        <div class="row d-flex justify-content-center">
                            <div class="col d-flex justify-content-center">
                                {% with "modal-"|add:product.htmlid as modalid %}
                                <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#{{modalid}}" data-pname="{{product.name}}" style="background-color: #c32434;">Add to Quote</button>
                                {% endwith %}
                            </div>
                            <div class="col d-flex justify-content-center">
                                <a href="{% url 'csf:download_file' product_id=product.id %}" type="button" class="btn btn-dark">Download Schematics</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <div class="card" style="width: 40rem; margin: 20px">
                    <div class="card-body" style="text-align: center;">
                        {% if selected_category == "none" %}
                            <h4>Your search returned no results.</h4>
                        {% else %}
                            <h4 style="color: silver;">Select a Product Range to begin browsing products.</h4>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

{#       QUOTE MODALS         #}
    {% for product in products %}
        {% with "modal-"|add:product.htmlid as modalid %}
        {% with "modal-label"|add:product.htmlid as modalabel %}
    <div class="modal fade" id="{{modalid}}" tabindex="-1" aria-labelledby="{{modalabel}}" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
      <form action="" method="post">
      {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="{{modalabel}}">Add {{product.name}} to quote:</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body d-flex justify-content-center" value="">
            <div class="col justify-content-center">
                <div class="row justify-content-center">
                    <span class="btn btn-dark" style="width: 8rem;">Select Size</span>
                </div>
                <div class="row" style="padding-top: 5px;"></div>
                <div class="row justify-content-center">
                    <span class="btn btn-dark" style="width: 8rem;">Enter Quantity</span>
                </div>
            </div>
            <div class="col justify-content-center">
                <div class="row justify-content-start">
                    <select name="size" class="form-select" aria-label="Default select example"  style="width: 10rem;">
                        <option selected>Sizes Available</option>
                        {% for item in product.sizes|process_sizes %}
                            <option value="{{ item }}">{{ item }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="row" style="padding-top: 5px;"></div>
                <div class="row justify-content-start">
                    <input name="quant" min="0" max="1000" type="number" class="form-control" value="1" style="width: 5rem">
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <input type="hidden" name="product_id" value="{{product.id}}"></input>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-dark" style="background-color: #c32434;">Add</button>
        </div>
      </form>
      </div>
    </div>
  </div>
        {% endwith %} {% endwith %}
    {% endfor %}
{% endblock %}

templates/sent.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap_icons %}
    <div class="container d-flex justify-content-center">
        <div class="card" style="width: 40rem; margin: 20px">
            <div class="card-header align-text-center">
                <h5 class="card-title">Quote Request Sent</h5>
            </div>
            <div class="card-body align-text-center">
                <p>Thank you for using the quote request system, you will be emailed a copy of your quote request.</p>
                <p>We will reach out to you soon regarding you quote.</p>
                <p> - The Carolina Steel Fabrication Team</p>
            </div>
            <div class="card-footer">
              <a href="/products" class="btn btn-secondary"><span style="padding-right: 5px;">{% bs_icon 'arrow-left' %}</span>Return to Products</a>
            </div>
        </div>
    </div>
{% endblock %}